from tkinter import *
top=Tk()
top.geometry("1400x800")
top.title("kitty")
top.config(bg="brown")
welcome=Label (top,text= "welcome to our page", font=('TimesNewRoman',25,'italic'),bg="brown",fg="white")
welcome.place(x=550,y=75)
def login():
    kit=Frame(top,bg="black",height=700,width=400)
    kit.pack(fill=X)
    label1=Label(kit,text="login page",font=('TimesNewRoman',25,'italic'),bg="black",fg="white")
    label1.place(x=650,y=100)
    label12=Label(kit,text="user name",bg="white",font=('TimesNewRoman',15,'italic'),fg="black")
    label12.place(x=675,y=350)
    box=Entry (kit,text=  "", font=('TimesNewRoman',20,'italic'),bg="white",fg="black")
    box.place(x=800,y=350,width=200,height=30)
    label12=Label(kit,text="password",bg="white",font=('TimesNewRoman',15,'italic'),fg="black")
    label12.place(x=675,y=400)
    box=Entry (kit,text=  "", font=('TimesNewRoman',20,'italic'),bg="white",fg="black")
    box.place(x=800,y=400,width=200,height=30)
    button=Button(top,text="login",font=('TimesNewRoman',20,'italic'),bg="blue",fg="white",activebackground="red",activeforeground="white",command=login)
    button.place(x=550,y=500,height=50,width=200)
    label12=Label(kit,text="don't have an account?",bg="white",font=('TimesNewRoman',15,'italic'),fg="black")
    label12.place(x=500,y=600)
    label12=Label(kit,text="sign in",bg="yellow",font=('TimesNewRoman',15,'italic'),fg="black")
    label12.place(x=750,y=600)
button=Button(top,text="get started",font=('TimesNewRoman',20,'italic'),bg="white",fg="black",activebackground="blue",activeforeground="black",command=login)
button.place(x=550,y=550,height=50,width=200)
top.mainloop()

